$jsonPath = "build\destinations.json"
$destinations = Get-Content -Raw -Path $jsonPath | ConvertFrom-Json

foreach ($dest in $destinations) {
    if ($dest.id -eq "greece") {
        $dest | Add-Member -MemberType NoteProperty -Name "article_1" -Value "More than 2000 islands make up Greece’s seascape, scattered across miles of coastline far from the mainland. It makes for memorable island hopping and every yacht charter different from the last. Though many islands are remote, some even without vehicles, accessibility by boat is surprisingly easy. Cruising by boat is the best way to discover isolated bays, enjoy picnics in solitude and make the most of water toys away from onlookers. Island hopping allows guests to experience the culture, immerse in the villages and dine on fine delicacies unique to certain areas." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_2" -Value "Greece offers the best of the Mediterranean climate, with mild winters and dry summers. Yachts typically charter during the summer months of June, July and August, though the bookend months of May and September can prove to be equally as rewarding once the heat has waned and the crowds have departed. Defined by the warm constant winds that blow throughout the year and rocky outcrops that harbor bays and paths ripe for discovery, the many isles sprinkled across the Aegean Sea create mesmeric yachting itineraries." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_3" -Value "Dripping in historic importance and renowned for the role it played in the progression of western civilization, Greece has many accolades to its name. From philosophers to Olympians, its culturally diverse lands beg to be explored one island at a time. The windmill island of Mykonos has earned an international reputation for its throbbing nightlife, while the glowing sunsets of Santorini melt hearts and minds. For a taste of Greek mythology, Apollo’s ancient seaside temple in Delos will deliver." -Force
    }
    if ($dest.id -eq "french-riviera") {
        $dest | Add-Member -MemberType NoteProperty -Name "article_1" -Value "The French Riviera, stretching from the glamour of Saint-Tropez to the exclusive enclave of Monaco, is the undisputed capital of European yachting. Cruising the Côte d'Azur provides unmatched access to Michelin-starred waterfront restaurants, elite beach clubs, and serene coastal beauty. Drop anchor off Cap Ferrat for a private swim in crystalline waters, or cruise past the iconic Promenade des Anglais in Nice before docking directly in the port of Cannes for an evening of luxury." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_2" -Value "Known for its endlessly sunny microclimate, the French Riviera enjoys mild winters and spectacularly warm, sun-drenched summers. The yachting season traditionally kicks off in May with the legendary Cannes Film Festival and Monaco Grand Prix, stretching beautifully until late September when the prestigious Monaco Yacht Show takes place. August is the undeniable peak, buzzing with mega-yachts and summer regattas, making early reservations absolutely essential for elite berthing." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_3" -Value "The Riviera is synonymous with artistic inspiration and high-society glamour. Wander the exact cobblestone alleys in Antibes where Picasso painted, or indulge in the fragrant perfume capital of Grasse nestled in the hills just above the coastline. The cultural fabric here is a breathtaking tapestry of old-world Belle Époque architecture seamlessly blended with the sharp, modern edge of the contemporary global elite that flock here every summer." -Force
    }
    if ($dest.id -eq "bahamas") {
        $dest | Add-Member -MemberType NoteProperty -Name "article_1" -Value "Comprised of 700 distinct coral islands and thousands of uninhabited cays, the Bahamas are custom-built for island hopping. Unlike deep-water regions, much of the Bahamian archipelago is incredibly shallow, making it the premier global playground for luxury catamarans and shallow-draft motor yachts. Snorkel the vibrant James Bond 'Thunderball Grotto', feed the famous swimming pigs at Big Major Cay, or sail the protected central Sea of Abaco where land is almost always in sight." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_2" -Value "While the Mediterranean sleeps out the winter, the Bahamas come alive. This is the ultimate winter escape, offering balmy, dry weather from November straight through to late May. The trade winds blow clear and consistently across the Exuma Sound, offering brilliant blue skies and water so stunningly transparent that yachts appear to be suspended in mid-air. Summer months are quieter but significantly hotter, transitioning into the tropical storm season." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_3" -Value "Bahamian culture is deeply tied to the rhythm of the sea and the legacy of its people. Nassau provides high-energy Junkanoo festivals, rich colonial history, and sprawling luxury casino resorts like Baha Mar. However, the true soul of the Bahamas is found in the 'Out Islands'—where generations of boat builders, conch divers, and friendly locals operate welcoming beachfront shacks serving up fresh conch salad, cracked lobster, and the beloved Bahama Mama cocktail under the shade of swaying palms." -Force
    }
    if ($dest.id -eq "caribbean") {
        $dest | Add-Member -MemberType NoteProperty -Name "article_1" -Value "From the sheltered, line-of-sight sailing in the British Virgin Islands to the dramatic, deep-water volcanic peaks of St. Lucia, the Caribbean offers a spectacularly diverse cruising ground. Superyachts frequently utilize St. Maarten or Antigua as central hubs before island-hopping down the Leeward chain, dropping anchor in the impossibly chic harbor of Gustavia in St. Barths, or escaping to the protected coral reefs of the Grenadines." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_2" -Value "The ultimate antidote to the Northern Hemisphere winter. The Caribbean yachting season operates opposite to the Mediterranean, reaching its absolute peak during the festive season (Christmas and New Year’s) and stretching through April. The consistent easterly trade winds provide ideal, predictable conditions for spectacular sailing yachts, while the lush, tropical climate keeps the ocean waters warm and inviting day and night." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_3" -Value "The Caribbean is an intricate mosaic of distinct sovereign nations, European territories, and vibrant local cultures. One day you may be dining on fine French cuisine and fresh croissants in Guadeloupe, and the next you are listening to authentic steel drum bands and sipping world-renowned aged rum in Antigua. Every island offers a unique cultural footprint heavily influenced by its colonial past, blended inextricably with robust Afro-Caribbean heritage." -Force
    }
    if ($dest.id -eq "italy") {
        $dest | Add-Member -MemberType NoteProperty -Name "article_1" -Value "Italy boasts over 4,500 miles of dramatic coastline, making it impossible to see entirely in one trip. The Amalfi Coast features gravity-defying villages clinging to sheer cliffs, providing stunning anchorages directly beneath towns like Positano and Ravello. Further west, the rugged island of Sardinia (and the exclusive Costa Smeralda) offers emerald waters and archipelago hopping, while the Italian Riviera in the north is defined by the colorful cliffside houses of Cinque Terre and Portofino." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_2" -Value "Italian summers are deeply entrenched in the concept of 'La Dolce Vita'. July and August represent the vibrant, electric peak of the season, where glamorous beach clubs in Capri and Ischia are packed with the global elite. For those looking to avoid the intense heat and the highest crowds, the shoulder season of September offers arguably the best yachting conditions; the sea has been warmed all summer, local harvests have begun, and the anchorages are wonderfully peaceful." -Force
        $dest | Add-Member -MemberType NoteProperty -Name "article_3" -Value "Cruising Italy is just as much a culinary and historical expedition as it is a beach vacation. Anchor off the coast of Naples for authentic Neapolitan pizza, sail the Sicilian coast tracing ancient Greek and Roman ruins, or tender into a coastal vineyard for a private tasting of world-class regional wines. The Italian approach to hospitality is warm, loud, and incredibly passionate, ensuring every moment ashore feels deeply authentic and culturally rewarding." -Force
    }
}

$destinations | ConvertTo-Json -Depth 5 -Compress | Set-Content -Path $jsonPath
Write-Host "JSON Updated with massive articles!"
